---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker build -t drone-demo:latest .

  - name: publish
    image: plugins/ecr
    volumes:
      - name: aws
        path: /root/.aws
    environment:
      AWS_DEFAULT_REGION: eu-west-1
      AWS_PROFILE: rimu
    settings:
      repo: drone-demo
      registry: 135132174985.dkr.ecr.eu-west-1.amazonaws.com
      tags:
        - latest

volumes:
  - name: aws
    host:
      path: /home/marlinf/.aws
  - name: docker
    host:
      path: /var/run/docker.sock
