---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker build -t drone-demo:latest .

  - name: publish
    image: plugins/ecr
    volumes:
      - name: aws
        path: /root/.aws
    settings:
      repo: drone-demo
      registry: 135132174985.dkr.ecr.eu-west-1.amazonaws.com
      tags:
        - latest

volumes:
  - name: aws
    host:
      path: $HOME/.aws
  - name: docker
    host:
      path: /var/run/docker.sock
